#!/bin/bash
chmod +x /usr/bin/wifipirata
chmod +x /usr/lib/wifipirata/bin/*.sh
chmod +x /usr/lib/wifipirata/modules/*.sh
chmod +x /usr/lib/wifipirata/utils/*.sh
echo "wifipirata instalado! Use 'wifipirata --help' para começar."
